{{- if .Values.service.tls.enabled }}
{{- $fullName := include "common.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
spec:
  secretName: {{ $fullName }}-tls
  duration: 2160h
  renewBefore: 2158h
  issuerRef:
    name: {{ .Values.service.tls.issuerName }}
    kind: ClusterIssuer
  dnsNames:
    - "{{ .Values.ingress.host }}"
{{- end }}