{{- $fullName := include "common.fullname" . -}}
{{- range $job := .Values.cronjob.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $fullName }}-{{ $job.name }}"
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ $job.backoffLimit | default "6" }}
      template:
        metadata:
          labels:
            app: {{ $fullName }}
            cron: {{ $job.name }}
        spec:
        {{- with $job.image.imagePullSecrets }}
          imagePullSecrets:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- if hasKey $job "serviceAccount" }}
        {{- if hasKey $job.serviceAccount "name" }}
          serviceAccountName: {{ $job.serviceAccount.name }}
        {{- else }}
          serviceAccountName: {{ $job.name }}
        {{- end }}
        {{- end }}
        {{- if hasKey $job "securityContext" }}
          {{- if $job.securityContext.runAsUser }}
          securityContext:
            runAsUser: {{ $job.securityContext.runAsUser }}
            {{- if $job.securityContext.runAsGroup }}
            runAsGroup: {{ $job.securityContext.runAsGroup }}
            {{- end }}
            {{- if $job.securityContext.fsGroup }}
            fsGroup: {{ $job.securityContext.fsGroup }}
            {{- end }}
          {{- end }}
        {{- end }}
          containers:
          - image: "{{ $job.image.repository }}:{{ $job.image.tag }}"
            imagePullPolicy: {{ $job.image.imagePullPolicy }}
            name: {{ $job.name }}
            {{- with $job.env }}
            env:
              {{- range $key, $value := . }}
              {{- if hasKey $value "type" }}
              - name: {{ $key | quote }}
              {{- if eq $value.type "kv" }}
                value: {{ $value.value | quote }}
              {{- else if eq $value.type "parameterStore" }}
                valueFrom:
                  secretKeyRef:
                    name: "{{ $fullName }}-{{ $value.name }}"
                    key: "{{ $fullName }}-{{ $value.name }}"
              {{- else if eq $value.type "configmapRef" }}
                valueFrom:
                  configMapKeyRef:
                    name: {{ $value.name | quote }}
                    key: {{ $value.key | quote }}
              {{- end }}
              {{- else }}
              - name: {{ $value.name | quote }}
                value: {{ $value.value | quote }}
              {{- end }}
              {{- end }}
            {{- end }}
            {{- with $job.envFrom }}
            envFrom:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- if $job.command }}
            command: {{ $job.command }}
            {{- end }}
            {{- with $job.args }}
            args:
{{ toYaml . | indent 12 }}
              {{- end }}
            {{- with $job.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with $job.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- with $job.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ $job.restartPolicy }}
          {{- with $job.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
{{- end }}
