{{- if .Values.ingress.enabled -}}
{{- $fullName := include "common.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
spec:
  ingressClassName: traefik
  {{- if .Values.service.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ $fullName }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
{{- end }}