{{- if .Values.httpWwwRedirect.enabled }}
{{- $fullName := include "common.fullname" . -}}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-http-www-redirect
spec:
  redirectRegex:
    permanent: true
    regex: ^(http)://(www\\.)?(.*)
    replacement: https://$3
{{- end }}
