{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
spec:
  secretName: ingress-tls
  duration: 2160h
  renewBefore: 2158h
  issuerRef:
    name: {{ .Values.ingress.tls.issuerName }}
    kind: ClusterIssuer
  dnsNames:
  {{- range .Values.ingress.hosts }}
    - {{ . | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.ingressIndex.enabled .Values.ingressIndex.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingressIndex-cert
spec:
  secretName: ingressIndex-tls
  duration: 2160h
  renewBefore: 2158h
  issuerRef:
    name: {{ .Values.ingressIndex.tls.issuerName }}
    kind: ClusterIssuer
  dnsNames:
  {{- range .Values.ingressIndex.hosts }}
    - {{ . | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.ingressRpc.enabled .Values.ingressRpc.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingressRpc-cert
spec:
  secretName: ingressRpc-tls
  duration: 2160h
  renewBefore: 2158h
  issuerRef:
    name: {{ .Values.ingressRpc.tls.issuerName }}
    kind: ClusterIssuer
  dnsNames:
  {{- range .Values.ingressRpc.hosts }}
    - {{ . | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.ingressWebsocket.enabled .Values.ingressWebsocket.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingressWebsocket-cert
spec:
  secretName: ingressWebsocket-tls
  duration: 2160h
  renewBefore: 2158h
  issuerRef:
    name: {{ .Values.ingressWebsocket.tls.issuerName }}
    kind: ClusterIssuer
  dnsNames:
  {{- range .Values.ingressWebsocket.hosts }}
    - {{ . | quote }}
  {{- end }}
{{- end }}
